trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureServiceConnection: 'nexeagle-dev-intra'
  webAppName: 'cms-api-dev'
  buildConfiguration: 'Release'
  dotnetVersion: '8.x'
  solutionPath: 'CMSAPI.sln'
  apiProjectPath: 'CMSAPI/CMSAPI.csproj'
  publishDir: '$(Build.ArtifactStagingDirectory)/publish'

stages:

# BUILD STAGE
- stage: Build
  jobs:
  - job: BuildJob
    steps:

    - checkout: self

    - task: UseDotNet@2
      inputs:
        packageType: sdk
        version: $(dotnetVersion)

    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: restore
        projects: $(solutionPath)

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: build
        projects: $(solutionPath)
        arguments: --configuration $(buildConfiguration) --no-restore

    - task: DotNetCoreCLI@2
      displayName: Publish
      inputs:
        command: publish
        publishWebProjects: false
        projects: $(apiProjectPath)
        arguments: --configuration $(buildConfiguration) --output $(publishDir) --no-build --no-restore
        modifyOutputPath: false

    - task: PublishBuildArtifacts@1
      displayName: Publish Artifact
      inputs:
        PathtoPublish: $(publishDir)
        ArtifactName: drop


# DEPLOY STAGE
- stage: Deploy
  dependsOn: Build
  jobs:
  - deployment: DeployWeb
    environment: development
    strategy:
      runOnce:
        deploy:
          steps:

          - download: current
            artifact: drop

          - task: AzureWebApp@1
            displayName: Deploy to Azure
            inputs:
              azureSubscription: $(azureServiceConnection)
              appType: webApp
              appName: $(webAppName)
              package: $(Pipeline.Workspace)/drop
              deploymentMethod: runFromPackage
